package com.example.rmc_app.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF704DA0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEDDCFF)
val md_theme_light_onPrimaryContainer = Color(0xFF290055)
val md_theme_light_secondary = Color(0xFF645A70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBDDF7)
val md_theme_light_onSecondaryContainer = Color(0xFF20182A)
val md_theme_light_tertiary = Color(0xFF7F525A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DF)
val md_theme_light_onTertiaryContainer = Color(0xFF321019)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2E004E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2E004E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_inverseOnSurface = Color(0xFFFBECFF)
val md_theme_light_inverseSurface = Color(0xFF461968)
val md_theme_light_inversePrimary = Color(0xFFD8B9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF704DA0)
val md_theme_light_outlineVariant = Color(0xFFCCC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD8B9FF)
val md_theme_dark_onPrimary = Color(0xFF401B6E)
val md_theme_dark_primaryContainer = Color(0xFF573486)
val md_theme_dark_onPrimaryContainer = Color(0xFFEDDCFF)
val md_theme_dark_secondary = Color(0xFFCFC2DA)
val md_theme_dark_onSecondary = Color(0xFF352D40)
val md_theme_dark_secondaryContainer = Color(0xFF4C4357)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBDDF7)
val md_theme_dark_tertiary = Color(0xFFF2B7C1)
val md_theme_dark_onTertiary = Color(0xFF4B252D)
val md_theme_dark_tertiaryContainer = Color(0xFF653B43)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2E004E)
val md_theme_dark_onBackground = Color(0xFFF2DAFF)
val md_theme_dark_surface = Color(0xFF2E004E)
val md_theme_dark_onSurface = Color(0xFFF2DAFF)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC4CF)
val md_theme_dark_outline = Color(0xFF958E99)
val md_theme_dark_inverseOnSurface = Color(0xFF2E004E)
val md_theme_dark_inverseSurface = Color(0xFFF2DAFF)
val md_theme_dark_inversePrimary = Color(0xFF704DA0)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD8B9FF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF3B1D62)
